# SHA3x Miner - Free and Open Source Software Statement
#
# This project, sha3x-miner, is Free and Open Source Software (FOSS) licensed
# under the MIT License. You are free to use, modify, and distribute this
# software in accordance with the license terms. Contributions are welcome
# via pull requests to the project repository.
#
# File: Cargo.toml
# Version: 1.0.1
# Developer: OIEIEIO <oieieio@protonmail.com>
#
# This file is the configuration for the SHA3x miner project, located at the
# root of the project tree. It defines metadata, dependencies, features, and
# binary targets for building the miner, supporting both SHA3X (Tari) and SHA-256 (Bitcoin).
#
# Tree Location:
# - Cargo.toml (project configuration file)
# - Depends on: none

[package]
name = "sha3x-miner"
version = "1.0.0"
edition = "2024"
description = "High-performance SHA3x (Tari) and SHA-256 (Bitcoin) CPU miner"
license = "MIT"
# repository = "https://github.com/your-repo/sha3x-miner"  # Uncomment and set your repo
rust-version = "1.85"  # Meets 2024 edition requirement

[dependencies]
# Core dependencies
sha3 = "0.10.8"  # Stable version for SHA3X
sha2 = "0.10.8"  # Added for SHA-256
hex = "0.4.3"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
clap = { version = "4.5.18", features = ["derive"] }
num_cpus = "1.16.0"
rand = "0.8.5"
crossbeam = "0.8.4"
uint = "0.10.0"
axum = { version = "0.7", features = ["ws"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["fs", "cors"] }
tokio-tungstenite = "0.21"
sysinfo = "0.35.2"

# SV2 from git repository 
roles_logic_sv2 = { git = "https://github.com/stratum-mining/stratum", branch = "main" }
codec_sv2 = { git = "https://github.com/stratum-mining/stratum", branch = "main" }
binary_sv2 = { git = "https://github.com/stratum-mining/stratum", branch = "main" }
framing_sv2 = { git = "https://github.com/stratum-mining/stratum", branch = "main" }
noise_sv2 = { git = "https://github.com/stratum-mining/stratum", branch = "main" }

# Async channels
async-channel = "1.8"


# TUI dependencies (optional)
ratatui = { version = "0.29.0", optional = true }
crossterm = { version = "0.28.1", optional = true }

[features]
default = []
tui = ["ratatui", "crossterm"]

[[bin]]
name = "sha3x-miner"
path = "src/main.rs"

# Changelog:
# - v1.0.1 (2025-06-15): Added SHA-256 support.
#   - Added sha2 = "0.10.8" dependency for SHA-256 algorithm implementation.
#   - Updated package description to include SHA-256 and Bitcoin support.
# - v1.0.0 (2025-06-14): Initial configuration for modular breakout.
#   - Purpose: Configures the sha3x-miner project, specifying metadata,
#     dependencies, and build settings for the CPU miner.
#   - Features: Defines dependencies for core mining (e.g., sha3, tokio),
#     optional TUI support via feature flag, and a single binary target.
#     Sets rust-version to 1.85 for 2024 edition compatibility.
#   - Note: Updated sha3 to 0.10.8 for stable dependency resolution, ensuring
#     compatibility with SHA3x hashing requirements.